name: zip datapack

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every release
  push:
    tags:
    - '*'

jobs:
  zip:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # zip the file
    - name: Create Zip Folder
      run: zip -r datapack.zip . -x ".git/*" ".github/*"
    # get latest release
    - id: release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
    # release on github
    - name: Release to github
      uses: xresloader/upload-to-github-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "datapack.zip"
        delete_file: "datapack.zip"
        release_id: ${{ steps.release.outputs.id }}
        # tags: ${{ github.ref }}
        overwrite: true
        verbose: true
